//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Sankhya.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Sankhya.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all pages loaded.
        /// </summary>
        internal static string AllPagesLoaded {
            get {
                return ResourceManager.GetString("AllPagesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is already disposed.
        /// </summary>
        internal static string AlreadyDisposed {
            get {
                return ResourceManager.GetString("AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new items to a cancelled on demand request wrapper instance.
        /// </summary>
        internal static string CancelledOnDemandRequestWrapperException {
            get {
                return ResourceManager.GetString("CancelledOnDemandRequestWrapperException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to confirm invoice with single number: {0}.
        /// </summary>
        internal static string ConfirmInvoiceException {
            get {
                return ResourceManager.GetString("ConfirmInvoiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating/updating.
        /// </summary>
        internal static string CreatingOrUpdating {
            get {
                return ResourceManager.GetString("CreatingOrUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting.
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} has multiple attributes of type {1}.
        /// </summary>
        internal static string EntityExtensions_GetEntityCustomData {
            get {
                return ResourceManager.GetString("EntityExtensions_GetEntityCustomData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must inherits from {1} or must be of type {2}.
        /// </summary>
        internal static string EntityExtensions_TypeMustInherits {
            get {
                return ResourceManager.GetString("EntityExtensions_TypeMustInherits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiscal invoice status.
        /// </summary>
        internal static string FiscalInvoiceStatus {
            get {
                return ResourceManager.GetString("FiscalInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; requires the application for the client {1}.
        /// </summary>
        internal static string InvalidClientEntityException {
            get {
                return ResourceManager.GetString("InvalidClientEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied key {0} is not valid for this session or has been deleted from the Sankhya.
        /// </summary>
        internal static string InvalidKeyFileException {
            get {
                return ResourceManager.GetString("InvalidKeyFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use query options with service {0}.
        /// </summary>
        internal static string InvalidServiceQueryOptionsException {
            get {
                return ResourceManager.GetString("InvalidServiceQueryOptionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute this operation with service {0}.
        /// </summary>
        internal static string InvalidServiceRequestOperationException {
            get {
                return ResourceManager.GetString("InvalidServiceRequestOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string ItemPluralSufix {
            get {
                return ResourceManager.GetString("ItemPluralSufix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} ite{2} to invoice with single number {1}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_AddInvoiceItems_AddingItemsToInvoice {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_AddInvoiceItems_AddingItemsToInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing the invoice with single number {0} to TOP {1} | Billing type: {2} | Series: {3}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_Bill_BillingInvoiceToTOP {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_Bill_BillingInvoiceToTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding invoice with single number {0} with order. Partner code: {1} | Movement type: {2}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_BindInvoiceWithOrder {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_BindInvoiceWithOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invoice{1} canceled.
        /// </summary>
        internal static string KnowServicesRequestWrapper_CancelInvoices_Canceled {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_CancelInvoices_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling {0} invoice{1} with single number{1} {2}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_CancelInvoices_Canceling {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_CancelInvoices_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming invoice with single number: {0}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_ConfirmInvoice_Confirming {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_ConfirmInvoice_Confirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating invoice header for operation {0} with {1} ite{2}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_CreateInvoice {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_CreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0} files from repository.
        /// </summary>
        internal static string KnowServicesRequestWrapper_DeleteFiles {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice with single number {0} duplicated, new invoice with single number: {1}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_DuplicateInvoice_Duplicated {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_DuplicateInvoice_Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicating invoice with single number {0} on TOP: {1} | series: {2} | exit date: {3} | update prices: {4}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_DuplicateInvoice_Duplicating {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_DuplicateInvoice_Duplicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagging financial movement{0} as paid: {1}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_FlagAsPaymentsPaid {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_FlagAsPaymentsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagging {0} invoice{1} with single number{1} {2} as not pending.
        /// </summary>
        internal static string KnowServicesRequestWrapper_FlagInvoicesAsNotPending {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_FlagInvoicesAsNotPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating lot of {0} fiscal invoice{1} with single number{1} {2}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_GenerateLot {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_GenerateLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting authorization of {0} fiscal invoice{1} with single number{1} {2}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_GetFiscalInvoiceAuthorization {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_GetFiscalInvoiceAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting accompaniments of {0} invoice{1} with single number{1} {2}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_GetInvoiceAccompaniments {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_GetInvoiceAccompaniments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving messages.
        /// </summary>
        internal static string KnowServicesRequestWrapper_ReceiveMessages_ReceivingMessages {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_ReceiveMessages_ReceivingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing invoice with single number {0}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_RemoveInvoice {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_RemoveInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items must be from the same invoice.
        /// </summary>
        internal static string KnowServicesRequestWrapper_RemoveInvoiceItems_AllItemsMustBeFromTheSameInvoice {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_RemoveInvoiceItems_AllItemsMustBeFromTheSameInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0} ite{2} from invoice with single number {1}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_RemoveInvoiceItems_DeletingItemsFromInvoice {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_RemoveInvoiceItems_DeletingItemsFromInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing financial low of movement with single number {0}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_ReversePayments {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_ReversePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message to {0} users/groups.
        /// </summary>
        internal static string KnowServicesRequestWrapper_SendMessage_SendingMessage {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_SendMessage_SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending warning with level {0} and title {1} to {2}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_SendWarning_SendingWarningWithLevel {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_SendWarning_SendingWarningWithLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink the shipping for the financial single number {0}.
        /// </summary>
        internal static string KnowServicesRequestWrapper_UnlinkShipping {
            get {
                return ResourceManager.GetString("KnowServicesRequestWrapper_UnlinkShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to low payments for financial numbers {0}.
        /// </summary>
        internal static string MarkAsPaymentPaidException {
            get {
                return ResourceManager.GetString("MarkAsPaymentPaidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property of {1} entity (Type: {2}) is missing the serializer helper method.
        /// </summary>
        internal static string MissingSerializerHelperEntityException {
            get {
                return ResourceManager.GetString("MissingSerializerHelperEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice {0} has no items, cannot be confirmed.
        /// </summary>
        internal static string NoItemsConfirmInvoiceException {
            get {
                return ResourceManager.GetString("NoItemsConfirmInvoiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fiscal invoice {0} with {1} {2} does not allow correction.
        /// </summary>
        internal static string NotAllowedCorrectionFiscalInvoiceException {
            get {
                return ResourceManager.GetString("NotAllowedCorrectionFiscalInvoiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of {0}.
        /// </summary>
        internal static string OfTotal {
            get {
                return ResourceManager.GetString("OfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding item of type {0} to queue.
        /// </summary>
        internal static string OnDemandRequestWrapper_Add {
            get {
                return ResourceManager.GetString("OnDemandRequestWrapper_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} request{1} done for sending {2} entit{3} (successful: {5}) of type {4}.
        /// </summary>
        internal static string OnDemandRequestWrapper_Dispose {
            get {
                return ResourceManager.GetString("OnDemandRequestWrapper_Dispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emptying the queue of type {0}.
        /// </summary>
        internal static string OnDemandRequestWrapper_Flush {
            get {
                return ResourceManager.GetString("OnDemandRequestWrapper_Flush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling queue for type {0} with session token {1}.
        /// </summary>
        internal static string OnDemandRequestWrapper_OnDemandRequestWrapper_Cancelling {
            get {
                return ResourceManager.GetString("OnDemandRequestWrapper_OnDemandRequestWrapper_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting queue for the type {0} with throughput of {1} ite{2}.
        /// </summary>
        internal static string OnDemandRequestWrapper_OnDemandRequestWrapper_Starting {
            get {
                return ResourceManager.GetString("OnDemandRequestWrapper_OnDemandRequestWrapper_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ite{2} of type {3}.
        /// </summary>
        internal static string OnDemandRequestWrapper_Process {
            get {
                return ResourceManager.GetString("OnDemandRequestWrapper_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation type.
        /// </summary>
        internal static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were one or more errors in the paged request below.
        /// </summary>
        internal static string PagedRequestException {
            get {
                return ResourceManager.GetString("PagedRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entit{1} loaded of type {2}.
        /// </summary>
        internal static string PagedRequestWrapper_Close {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got {0} items of {1} in {2}.
        /// </summary>
        internal static string PagedRequestWrapper_GetManagedEnumerator {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_GetManagedEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred when loading paged request of type {0}.
        /// </summary>
        internal static string PagedRequestWrapper_GetManagedEnumerator_ErrorOccured {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_GetManagedEnumerator_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}{1} for paged request of {2} loaded with {3} entit{4}.
        /// </summary>
        internal static string PagedRequestWrapper_GetManagedEnumerator_PageLoaded {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_GetManagedEnumerator_PageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object disposed ignored.
        /// </summary>
        internal static string PagedRequestWrapper_GetManagedEnumeratorInternal {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_GetManagedEnumeratorInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation requested for request {0} {1} {2}.
        /// </summary>
        internal static string PagedRequestWrapper_HandleCancellationTokenCancelled {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_HandleCancellationTokenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting another paged request of type {0} end. Estimated time to wait: {1}.
        /// </summary>
        internal static string PagedRequestWrapper_LoadResponse_Waiting {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_LoadResponse_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signaling &apos;{1}&apos; event of type {0} for anyone who wants to listen.
        /// </summary>
        internal static string PagedRequestWrapper_Signaling {
            get {
                return ResourceManager.GetString("PagedRequestWrapper_Signaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page loaded.
        /// </summary>
        internal static string PageLoaded {
            get {
                return ResourceManager.GetString("PageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove invoice with single number: {0}.
        /// </summary>
        internal static string RemoveInvoiceException {
            get {
                return ResourceManager.GetString("RemoveInvoiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response stream is null.
        /// </summary>
        internal static string ResponseStreamIsNull {
            get {
                return ResourceManager.GetString("ResponseStreamIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting new session for {0} requests.
        /// </summary>
        internal static string SankhyaContext_AcquireNewSession_NewSession {
            get {
                return ResourceManager.GetString("SankhyaContext_AcquireNewSession_NewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New session started for {0} requests with token {1}.
        /// </summary>
        internal static string SankhyaContext_AcquireNewSession_NewSessionStarted {
            get {
                return ResourceManager.GetString("SankhyaContext_AcquireNewSession_NewSessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing service context.
        /// </summary>
        internal static string SankhyaContext_Dispose_DisposingServiceContext {
            get {
                return ResourceManager.GetString("SankhyaContext_Dispose_DisposingServiceContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing session with token {0}.
        /// </summary>
        internal static string SankhyaContext_FinalizeSession_FinalizeSession {
            get {
                return ResourceManager.GetString("SankhyaContext_FinalizeSession_FinalizeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating on Sankhya web service with username: {0}.
        /// </summary>
        internal static string SankhyaWrapper_Authenticate_Authentication {
            get {
                return ResourceManager.GetString("SankhyaWrapper_Authenticate_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting file with key {0}.
        /// </summary>
        internal static string SankhyaWrapper_GetFile_Getting {
            get {
                return ResourceManager.GetString("SankhyaWrapper_GetFile_Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting image on entity {0} with keys: {1}.
        /// </summary>
        internal static string SankhyaWrapper_GetImage_Getting {
            get {
                return ResourceManager.GetString("SankhyaWrapper_GetImage_Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found at {0}.
        /// </summary>
        internal static string SankhyaWrapper_GetImage_ImageNotFound {
            get {
                return ResourceManager.GetString("SankhyaWrapper_GetImage_ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid read size.
        /// </summary>
        internal static string SankhyaWrapper_ReadStream_Exception {
            get {
                return ResourceManager.GetString("SankhyaWrapper_ReadStream_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query canceled, probably overloaded on server. Taking {0} seconds to retry..
        /// </summary>
        internal static string SankhyaWrapper_ServiceInvokerInternal_CanceledQuery {
            get {
                return ResourceManager.GetString("SankhyaWrapper_ServiceInvokerInternal_CanceledQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceInvoker -&gt; Module: {0} | Service: {1} | Attempt: {2}.
        /// </summary>
        internal static string SankhyaWrapper_ServiceInvokerInternal_Module {
            get {
                return ResourceManager.GetString("SankhyaWrapper_ServiceInvokerInternal_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} identified, taking {0} seconds to retry.
        /// </summary>
        internal static string SankhyaWrapper_ServiceInvokerInternal_ReasonIdentifiedTakingSecondsRetry {
            get {
                return ResourceManager.GetString("SankhyaWrapper_ServiceInvokerInternal_ReasonIdentifiedTakingSecondsRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceInvoker -&gt; Service: {0} | Entity: {1} | Attempt: {2}.
        /// </summary>
        internal static string SankhyaWrapper_ServiceInvokerInternal_Service {
            get {
                return ResourceManager.GetString("SankhyaWrapper_ServiceInvokerInternal_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sankhya-W application version: {0}.
        /// </summary>
        internal static string SankhyaWrapper_ShowVersionInfo_SankhyaWVersion {
            get {
                return ResourceManager.GetString("SankhyaWrapper_ShowVersionInfo_SankhyaWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sankhya-W version not found.
        /// </summary>
        internal static string SankhyaWrapper_ShowVersionInfo_SankhyaWVersionNotFound {
            get {
                return ResourceManager.GetString("SankhyaWrapper_ShowVersionInfo_SankhyaWVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} requires the attribute {1}.
        /// </summary>
        internal static string ServiceRequestAttributeException {
            get {
                return ResourceManager.GetString("ServiceRequestAttributeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The business rule {0} doesn&apos;t allow the request to be completed. Error message: {1}.
        /// </summary>
        internal static string ServiceRequestBusinessRuleRestrictionException {
            get {
                return ResourceManager.GetString("ServiceRequestBusinessRuleRestrictionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has been identified as duplicated by Sankhya.
        /// </summary>
        internal static string ServiceRequestCompetitionException {
            get {
                return ResourceManager.GetString("ServiceRequestCompetitionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partner {0} has the document duplicated with another partner.
        /// </summary>
        internal static string ServiceRequestDuplicatedDocumentException {
            get {
                return ResourceManager.GetString("ServiceRequestDuplicatedDocumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s session is expired.
        /// </summary>
        internal static string ServiceRequestExpiredAuthenticationException {
            get {
                return ResourceManager.GetString("ServiceRequestExpiredAuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider changing the inline reference {0}.{1} for EntityReference in property {2} of entity {3} (Type: {4}).
        /// </summary>
        internal static string ServiceRequestExtensions_ParseProperty {
            get {
                return ResourceManager.GetString("ServiceRequestExtensions_ParseProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Sankhya error (NPE) on call to the {0} service. Check Sankhya log file for more information.
        /// </summary>
        internal static string ServiceRequestExternalException {
            get {
                return ResourceManager.GetString("ServiceRequestExternalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the file from path {0}. File or directory not found..
        /// </summary>
        internal static string ServiceRequestFileNotFoundException {
            get {
                return ResourceManager.GetString("ServiceRequestFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value supplied to {0}.{1} reference isn&apos;t valid..
        /// </summary>
        internal static string ServiceRequestForeignKeyException {
            get {
                return ResourceManager.GetString("ServiceRequestForeignKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction logs of &apos;{0}&apos; database is full.
        /// </summary>
        internal static string ServiceRequestFullTransactionLogsException {
            get {
                return ResourceManager.GetString("ServiceRequestFullTransactionLogsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Sankhya server at address {0}:{1}.
        /// </summary>
        internal static string ServiceRequestInaccessibleException {
            get {
                return ResourceManager.GetString("ServiceRequestInaccessibleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt of unauthorized/unauthenticated access.
        /// </summary>
        internal static string ServiceRequestInvalidAuthorizationException {
            get {
                return ResourceManager.GetString("ServiceRequestInvalidAuthorizationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate in Sankhya web service with provided credentials data.
        /// </summary>
        internal static string ServiceRequestInvalidCredentialsException {
            get {
                return ResourceManager.GetString("ServiceRequestInvalidCredentialsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter expression &apos;{0}&apos; is invalid, check if it is a valid SQL expression!.
        /// </summary>
        internal static string ServiceRequestInvalidExpressionException {
            get {
                return ResourceManager.GetString("ServiceRequestInvalidExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the service response.
        /// </summary>
        internal static string ServiceRequestInvalidOperationException {
            get {
                return ResourceManager.GetString("ServiceRequestInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relation {0} of entity {1} cannot be found on Sankhya.
        /// </summary>
        internal static string ServiceRequestInvalidRelationException {
            get {
                return ResourceManager.GetString("ServiceRequestInvalidRelationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subquery returned more than 1 value. This is not allowed when the subquery follows a =,! =, &lt;, &lt;=,&gt;,&gt; = or when it is used as an expression.
        /// </summary>
        internal static string ServiceRequestInvalidSubQueryException {
            get {
                return ResourceManager.GetString("ServiceRequestInvalidSubQueryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the paged request, concurrent requests from the same user causes this error.
        /// </summary>
        internal static string ServiceRequestPaginationException {
            get {
                return ResourceManager.GetString("ServiceRequestPaginationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the absence of the State registration, only the ICMS Classification: &apos;Non - Contributing Final Consumer&apos; and &apos;Rural Producer&apos; are permitted.
        /// </summary>
        internal static string ServiceRequestPartnerFiscalClassificationException {
            get {
                return ResourceManager.GetString("ServiceRequestPartnerFiscalClassificationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partner document have an invalid length.
        /// </summary>
        internal static string ServiceRequestPartnerInvalidDocumentLengthException {
            get {
                return ResourceManager.GetString("ServiceRequestPartnerInvalidDocumentLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the word ISENTO for this type of state registration.
        /// </summary>
        internal static string ServiceRequestPartnerStateInscriptionException {
            get {
                return ResourceManager.GetString("ServiceRequestPartnerStateInscriptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the service {0} couldn&apos;t find the field {1} on entity {2} in {3} entity request.
        /// </summary>
        internal static string ServiceRequestPropertyNameException {
            get {
                return ResourceManager.GetString("ServiceRequestPropertyNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the service {0} couldn&apos;t find the field {1} on entity {2}.
        /// </summary>
        internal static string ServiceRequestPropertyValueException {
            get {
                return ResourceManager.GetString("ServiceRequestPropertyValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the service {0} couldn&apos;t be completed because the width of the value for  the {1} property on entity {2} is above that allowed. Current width: {3}. Width allowed: {4}.
        /// </summary>
        internal static string ServiceRequestPropertyWidthException {
            get {
                return ResourceManager.GetString("ServiceRequestPropertyWidthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use a managed request object that was already consumed.
        /// </summary>
        internal static string ServiceRequestRepeatedException {
            get {
                return ResourceManager.GetString("ServiceRequestRepeatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the {0} service has timed out.
        /// </summary>
        internal static string ServiceRequestTimeoutException {
            get {
                return ResourceManager.GetString("ServiceRequestTimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request to {0} service on entity {1} resulted in {2} entities as a result. The expected was only one entity.
        /// </summary>
        internal static string ServiceRequestTooManyResultsException {
            get {
                return ResourceManager.GetString("ServiceRequestTooManyResultsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the {0} service is currently unavailable.
        /// </summary>
        internal static string ServiceRequestUnavailableException {
            get {
                return ResourceManager.GetString("ServiceRequestUnavailableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unbalanced delimiter in the request.
        /// </summary>
        internal static string ServiceRequestUnbalancedDelimiterException {
            get {
                return ResourceManager.GetString("ServiceRequestUnbalancedDelimiterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the {0} service resulted in an invalid response.
        /// </summary>
        internal static string ServiceRequestUnexpectedResultException {
            get {
                return ResourceManager.GetString("ServiceRequestUnexpectedResultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the {0} service resulted in the following uncaught error message: {1}.
        /// </summary>
        internal static string ServiceRequestUnexpectedResultException_Uncaught {
            get {
                return ResourceManager.GetString("ServiceRequestUnexpectedResultException_Uncaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; element is not currently being addressed in Service Response.ResponseBody for the {1} service.
        /// </summary>
        internal static string ServiceResponseUnexpectedElementException {
            get {
                return ResourceManager.GetString("ServiceResponseUnexpectedElementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have between 1 and 6 digits.
        /// </summary>
        internal static string TheValueMustHaveBetween1and6digits {
            get {
                return ResourceManager.GetString("TheValueMustHaveBetween1and6digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninformed.
        /// </summary>
        internal static string Uninformed {
            get {
                return ResourceManager.GetString("Uninformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unlink shipping for financial numbers {0}.
        /// </summary>
        internal static string UnlinkShippingException {
            get {
                return ResourceManager.GetString("UnlinkShippingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  users/groups.
        /// </summary>
        internal static string UsersOrGroups {
            get {
                return ResourceManager.GetString("UsersOrGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ies.
        /// </summary>
        internal static string YPluralSuffix {
            get {
                return ResourceManager.GetString("YPluralSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string YSingularSuffix {
            get {
                return ResourceManager.GetString("YSingularSuffix", resourceCulture);
            }
        }
    }
}
